name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 0,6,12,18 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        mkdir -p "$(date +'%Y/%m/%d')"
        curl https://yle.fi/selkouutiset -o "$(date +'%Y/%m/%d/selkouutiset_%Y_%m_%d.html')"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push https://${GH_TOKEN}@github.com/${{ github.repository }}
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
